"""Base strategy class for the Kraken Trading Bot."""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from typing import Any

from kraken_api.models import Candle, OrderBook, Ticker

_LOGGER = logging.getLogger(__name__)


@dataclass
class Signal:
    """A trading signal generated by a strategy."""

    action: str  # "buy", "sell", or "hold"
    pair: str
    volume: Decimal | None = None
    price: Decimal | None = None  # None for market orders
    reason: str = ""
    timestamp: datetime = field(default_factory=datetime.utcnow)

    @property
    def is_actionable(self) -> bool:
        """Return True if this signal requires an action (not hold)."""
        return self.action in ("buy", "sell")


@dataclass
class StrategyState:
    """Persistent state for a trading strategy.

    Strategies can store arbitrary state that persists across ticks,
    allowing them to track positions, indicators, and other data.
    """

    position: Decimal = Decimal("0")  # Current position size
    entry_price: Decimal | None = None  # Price when position was opened
    last_signal: Signal | None = None  # Last signal generated
    indicators: dict[str, Any] = field(default_factory=dict)  # Strategy-specific indicators

    def has_position(self) -> bool:
        """Return True if we have an open position."""
        return self.position != 0

    def is_long(self) -> bool:
        """Return True if we have a long position."""
        return self.position > 0

    def is_short(self) -> bool:
        """Return True if we have a short position."""
        return self.position < 0


class Strategy(ABC):
    """Abstract base class for trading strategies.

    All trading strategies must inherit from this class and implement
    the `tick` method, which is called on each iteration of the trading
    loop with new market data.

    Strategies should:
    1. Analyze the provided market data
    2. Generate a Signal (buy/sell/hold)
    3. Update their internal state

    Example:
        class MyStrategy(Strategy):
            def tick(self, data: dict) -> Signal:
                # Analyze data...
                return Signal(action="buy", pair="XBT/USD", volume=Decimal("0.01"))
    """

    def __init__(self, name: str) -> None:
        self.name = name
        self.state = StrategyState()
        self._logger = logging.getLogger(f"strategy.{name}")

    @abstractmethod
    def tick(self, data: dict[str, Any]) -> Signal:
        """Process market data and generate a trading signal.

        Args:
            data: Dictionary containing market data. Common keys:
                - "ticker": Current Ticker object (from kraken_api.models)
                - "candles": List of recent Candle objects (from kraken_api.models)
                - "order_book": Current OrderBook object (from kraken_api.models)

        Returns:
            A Signal indicating the recommended action.
        """
        ...

    def on_order_filled(self, order: Any) -> None:
        """Called when an order is filled.

        Override this to update strategy state after a successful fill.

        Args:
            order: The filled Order object (from kraken_api.models).
        """
        self._logger.info("Order filled: %s", order)

    def on_error(self, error: Exception) -> None:
        """Called when an error occurs during strategy execution.

        Override this to handle errors gracefully.

        Args:
            error: The exception that occurred.
        """
        self._logger.error("Strategy error: %s", error)

    def reset(self) -> None:
        """Reset the strategy state.

        Override this to implement custom reset logic.
        """
        self.state = StrategyState()
        self._logger.info("Strategy state reset")
